
# Environment 
MKDIR=mkdir
CP=cp
CCADMIN=CCadmin
PVMLIBS=/usr/lib/libpvm3.a
PVMDIRECTORY=/home/damien/pvm3/bin/LINUX64/

all:
	g++ main.cpp -o account  $(PVMLIBS)


# include project implementation makefile
include nbproject/Makefile-impl.mk

# include project make variables
include nbproject/Makefile-variables.mk
