
# Environment 
MKDIR=mkdir
CP=cp
CCADMIN=CCadmin
PVMLIBS=/usr/lib/libpvm3.a

all:
	g++ main.cpp client.cpp bankmap.cpp -o client  $(PVMLIBS)
	


# include project implementation makefile
include nbproject/Makefile-impl.mk

# include project make variables
include nbproject/Makefile-variables.mk
